---
- name: Remove old docker installations
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
    state: absent

- name: Install apt over https requirements
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Install docker apt repo gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add docker's apt repo
  apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: Install docker-ce
  apt:
    name: docker-ce
